use gpui::*;

actions!(
    readit,
    [
        Quit,
        Save,
        SaveAll,
        SaveAs,
        NewFile,
        NewFolder,
        OpenFile,
        OpenFolder,
        CloseTab,
        CloseAll,
        ReopenTab,
        NextTab,
        PreviousTab,
        QuickOpen,
        CommandPalette,
        FindInFiles,
        GoToLine,
        Find,
        Replace,
        ToggleSidebar,
        ToggleWrap,
        RenameFile,
        DeleteFile,
        RestoreDeleted,
        Reload,
        Compare,
        FocusExplorer,
        Escape,
        PickerUp,
        PickerDown,
        PickerAccept,
        ZoomIn,
        ZoomOut,
        ResetZoom,
        Back,
        Forward,
        Help,
        Definition,
        PeekDefinition,
        TypeDefinition,
        Implementation,
        References,
        DocumentSymbols,
        HoverInfo,
        PinCode
    ]
);

pub fn init(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("cmd-k cmd-p", PinCode, Some("Readit")),
        KeyBinding::new("f12", Definition, Some("Readit")),
        KeyBinding::new("alt-f12", PeekDefinition, Some("Readit")),
        KeyBinding::new("cmd-f12", TypeDefinition, Some("Readit")),
        KeyBinding::new("cmd-shift-f12", Implementation, Some("Readit")),
        KeyBinding::new("shift-f12", References, Some("Readit")),
        KeyBinding::new("cmd-shift-o", DocumentSymbols, Some("Readit")),
        KeyBinding::new("cmd-k cmd-i", HoverInfo, Some("Readit")),
        KeyBinding::new("alt-left", Back, Some("Readit && !Input")),
        KeyBinding::new("alt-right", Forward, Some("Readit && !Input")),
        KeyBinding::new("cmd-q", Quit, Some("Readit")),
        KeyBinding::new("cmd-s", Save, Some("Readit")),
        KeyBinding::new("cmd-alt-s", SaveAll, Some("Readit")),
        KeyBinding::new("cmd-shift-s", SaveAs, Some("Readit")),
        KeyBinding::new("cmd-n", NewFile, Some("Readit")),
        KeyBinding::new("cmd-o", OpenFile, Some("Readit")),
        KeyBinding::new("cmd-k cmd-o", OpenFolder, Some("Readit")),
        KeyBinding::new("cmd-w", CloseTab, Some("Readit")),
        KeyBinding::new("cmd-k cmd-w", CloseAll, Some("Readit")),
        KeyBinding::new("cmd-shift-t", ReopenTab, Some("Readit")),
        KeyBinding::new("ctrl-tab", NextTab, Some("Readit")),
        KeyBinding::new("ctrl-shift-tab", PreviousTab, Some("Readit")),
        KeyBinding::new("cmd-shift-]", NextTab, Some("Readit")),
        KeyBinding::new("cmd-shift-[", PreviousTab, Some("Readit")),
        KeyBinding::new("cmd-p", QuickOpen, Some("Readit")),
        KeyBinding::new("cmd-shift-p", CommandPalette, Some("Readit")),
        KeyBinding::new("cmd-shift-f", FindInFiles, Some("Readit")),
        KeyBinding::new("ctrl-g", GoToLine, Some("Readit")),
        KeyBinding::new("cmd-f", Find, Some("Readit")),
        KeyBinding::new("cmd-alt-f", Replace, Some("Readit")),
        KeyBinding::new("cmd-b", ToggleSidebar, Some("Readit")),
        KeyBinding::new("alt-z", ToggleWrap, Some("Readit")),
        KeyBinding::new("cmd-shift-e", FocusExplorer, Some("Readit")),
        KeyBinding::new("f2", RenameFile, Some("Explorer")),
        KeyBinding::new("cmd-backspace", DeleteFile, Some("Explorer")),
        KeyBinding::new("cmd-shift-backspace", RestoreDeleted, Some("Explorer")),
        KeyBinding::new("cmd-r", Reload, Some("Readit")),
        KeyBinding::new("cmd-alt-d", Compare, Some("Readit")),
        KeyBinding::new("cmd-=", ZoomIn, Some("Readit")),
        KeyBinding::new("cmd--", ZoomOut, Some("Readit")),
        KeyBinding::new("cmd-0", ResetZoom, Some("Readit")),
        KeyBinding::new("ctrl--", Back, Some("Readit")),
        KeyBinding::new("ctrl-shift--", Forward, Some("Readit")),
        KeyBinding::new("escape", Escape, Some("Readit")),
        KeyBinding::new("up", PickerUp, Some("Picker")),
        KeyBinding::new("down", PickerDown, Some("Picker")),
        KeyBinding::new("enter", PickerAccept, Some("Picker")),
        KeyBinding::new("escape", Escape, Some("Picker")),
    ]);
    cx.set_menus(vec![
        Menu {
            name: "Readit".into(),
            items: vec![
                MenuItem::action("キーボードショートカット", Help),
                MenuItem::separator(),
                MenuItem::action("Readitを終了", Quit),
            ],
        },
        Menu {
            name: "ファイル".into(),
            items: vec![
                MenuItem::action("新規ファイル", NewFile),
                MenuItem::action("新規フォルダ", NewFolder),
                MenuItem::action("ファイルを開く…", OpenFile),
                MenuItem::action("フォルダを開く…", OpenFolder),
                MenuItem::separator(),
                MenuItem::action("保存", Save),
                MenuItem::action("すべて保存", SaveAll),
                MenuItem::action("名前を付けて保存…", SaveAs),
                MenuItem::action("名前を変更…", RenameFile),
                MenuItem::action("ファイルを削除…", DeleteFile),
                MenuItem::action("削除したファイルを復元", RestoreDeleted),
                MenuItem::separator(),
                MenuItem::action("タブを閉じる", CloseTab),
                MenuItem::action("すべてのタブを閉じる", CloseAll),
                MenuItem::action("閉じたタブを開く", ReopenTab),
                MenuItem::action("再読込…", Reload),
            ],
        },
        Menu {
            name: "編集".into(),
            items: vec![
                MenuItem::action("元に戻す", gpui_component::input::Undo),
                MenuItem::action("やり直す", gpui_component::input::Redo),
                MenuItem::separator(),
                MenuItem::action("切り取り", gpui_component::input::Cut),
                MenuItem::action("コピー", gpui_component::input::Copy),
                MenuItem::action("貼り付け", gpui_component::input::Paste),
                MenuItem::action("すべて選択", gpui_component::input::SelectAll),
                MenuItem::separator(),
                MenuItem::action("検索", Find),
                MenuItem::action("置換…", Replace),
            ],
        },
        Menu {
            name: "表示".into(),
            items: vec![
                MenuItem::action("エクスプローラー", ToggleSidebar),
                MenuItem::action("折返し", ToggleWrap),
                MenuItem::action("差分比較", Compare),
                MenuItem::action("拡大", ZoomIn),
                MenuItem::action("縮小", ZoomOut),
                MenuItem::action("倍率を戻す", ResetZoom),
            ],
        },
        Menu {
            name: "移動".into(),
            items: vec![
                MenuItem::action("定義へ移動", Definition),
                MenuItem::action("定義を確認…", PeekDefinition),
                MenuItem::action("型定義へ移動", TypeDefinition),
                MenuItem::action("実装へ移動", Implementation),
                MenuItem::action("使用箇所を検索…", References),
                MenuItem::action("ファイル内のシンボル…", DocumentSymbols),
                MenuItem::action("型とドキュメント", HoverInfo),
                MenuItem::separator(),
                MenuItem::action("ファイルへ移動…", QuickOpen),
                MenuItem::action("行へ移動…", GoToLine),
                MenuItem::action("プロジェクト内を検索…", FindInFiles),
                MenuItem::action("次のタブ", NextTab),
                MenuItem::action("前のタブ", PreviousTab),
                MenuItem::action("戻る", Back),
                MenuItem::action("進む", Forward),
                MenuItem::action("コマンドパレット…", CommandPalette),
            ],
        },
    ]);
}
